### ISSUE TITLE
Update POSIX Dependency to 5.x

### ISSUE THREAD

**Issue by Tysonpower** [kkazuo/shelf_unix_domain_socket#1]
Hello, i just got an issue uodateing to DART 3.x with your lib.

POSIX 4.1.x doesen't seem to work with dart 3, i wasn't able to compile.

Updating the dependency to posix 5.x worked well, please update your pubspec to the following:

```
dependencies:
  posix: ^5.0.0

```

**Comment by kkazuo** [comment]
Fixed with shelf_unix_domain_socket ver 1.1.1 .
Thank you for your patience.
